on: [push, pull_request]

name: Test

jobs:
  build:
    name: Build & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
          # will try to use previous cache if there was a miss. Might still be useful, but increases
          # cache size continuously when updating dependencies. Disable if you want to avoid this
          restore-keys: ${{ runner.os }}-cargo-
      - run: cargo build
      # these will run even if the build fails
      - run: cargo test
        if: always()
      - run: cargo fmt --all -- --check
        if: always()
      - run: cargo clippy -- -D warnings
        if: always()